variables:
  buildConfiguration: "Release"
  sln: "./Minsk.sln"
  tests: "./Minsk.Tests/Minsk.Tests.csproj"

steps:
  - script: dotnet build --configuration $(buildConfiguration) $(sln)
    displayName: "dotnet build $(buildConfiguration)"
  - script: dotnet test $(tests) --logger "xunit;LogFileName=TestResults.xml"
    displayName: "dotnet test"